### ISSUE TITLE
Add thin grey lines between the stories in the category/topic sections.

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-publicsource#31]
"Add thin grey lines between the stories in the category/topic sections."

Let me know if any additional clarification is needed.

**Comment by benlk** [comment]
Light or dark grey? :p

**Comment by MirandaEcho** [comment]
Medium grey.

**Comment by MirandaEcho** [comment]
From Public Source: Yes, the homepage. Right now, we have thin grey lines inbetween stories in the topics section, we'd just like to transfer that look over to the new topic section. See attached image of how it currently looks

![unnamed (2)](https://user-images.githubusercontent.com/48263361/56910893-397f3f00-6a71-11e9-90fd-d9541d95c139.png)

**Comment by joshdarby** [comment]
This is ready in PR #33.
