### ISSUE TITLE
Deploy questions

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-publicsource#32]
From Natasha at Public Source:
"Is there anything I need to know about moving these changes to the parent site? Will anything change at all in terms of how our backend functions or current plugins we have installed, etc? We'll want to stick with using the classic editor for now (we use via a WP plugin) instead of switching to Gutenburg, our staff is just not ready to make that change."

**Comment by benlk** [comment]
Deploying these changes should not affect how their backend functions. They've got Classic Editor active, and this doesn't change that.
