### ISSUE TITLE
Create space on story pages for decks/subheads

### ISSUE THREAD

**Issue by MirandaEcho** [INN/umbrella-publicsource#36]
Located below headline and above byline.  Design sent from Public Source:
![sansserif-deck](https://user-images.githubusercontent.com/48263361/59069358-77476280-887c-11e9-970b-09bdde16d9ad.png)

**Comment by benlk** [comment]
Example post on staging: http://staging.classy-vegetable.flywheelsites.com/the-life-deportation-and-death-of-guatemalan-immigrant-manuel-brito/

This is ready for review.

**Comment by MirandaEcho** [comment]
Client Feedback:
- [ ] I agree the grey is better than the black in the mockup, but I think it's too bold. Can we try the same font-weight that is on some headline areas on the homepage (photo attached). My inspector is saying it's font-weight 700, but I doubt that. Looks like 300 or 400.

**Comment by MirandaEcho** [comment]
(the photo she attached didn't actually get attached, so I've asked her for it. I will post it when I get it)

**Comment by MirandaEcho** [comment]
![Screen Shot 2019-06-14 at 4 01 41 PM](https://user-images.githubusercontent.com/48263361/59536354-1ab9f800-8eb9-11e9-8604-cab7343138d1.png)

**Comment by benlk** [comment]
That change has now been deployed.
